[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.35.2"
serde = {version = "1.0.158", features = ["derive"]}
serde_json = "1.0.94"

[[bin]]
name = "rustboy"
path = "src/main.rs"
