[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.158", features = ["derive"]}
serde_json = "1.0.94"

[dependencies.sdl2]
version = "0.36.0"
default-features = false
features = ["ttf"]

[[bin]]
name = "rustboy"
path = "src/main.rs"
